# Generated by Django 5.2.1 on 2025-08-27 09:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_studio_latitude_studio_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='longitude',
        ),
        migrations.AddField(
            model_name='studio',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
