# Generated by Django 5.2.1 on 2025-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_remove_studio_latitude_remove_studio_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
