# Generated by Django 5.2.1 on 2025-10-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_studio_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
